'use client';

import React, { useState } from 'react';
import { Bot, Copy, Download, Check, Plus, Trash2, Shield } from 'lucide-react';
import { ToolDefinition } from '@/lib/tools/types';
import { useAuth } from '@/lib/context/AuthContext';
import { useToast } from '@/lib/context/ToastContext';

export function RobotsGeneratorTool({ tool }: { tool: ToolDefinition }) {
  const [sitemapUrl, setSitemapUrl] = useState('https://example.com/sitemap.xml');
  const [allowAll, setAllowAll] = useState(true);
  const [disallowPaths, setDisallowPaths] = useState<string[]>(['/admin', '/api/', '/checkout/']);
  const [newPath, setNewPath] = useState('');
  const [testUrl, setTestUrl] = useState('https://example.com/admin/dashboard');
  const [copied, setCopied] = useState(false);
  const { canUseTool, recordConversion } = useAuth();
  const { showToast } = useToast();

  const addDisallow = () => {
    if (newPath.trim() && !disallowPaths.includes(newPath.trim())) {
      setDisallowPaths([...disallowPaths, newPath.trim()]);
      setNewPath('');
    }
  };

  const removeDisallow = (path: string) => {
    setDisallowPaths(disallowPaths.filter((p) => p !== path));
  };

  const robotsTxtContent = `# robots.txt generated by Toolora (toolora.com)
User-agent: *
${allowAll ? 'Allow: /' : ''}
${disallowPaths.map((p) => `Disallow: ${p}`).join('\n')}

# Sitemap reference
Sitemap: ${sitemapUrl}`;

  const isTestUrlBlocked = disallowPaths.some((p) => {
    try {
      const parsed = new URL(testUrl);
      return parsed.pathname.startsWith(p);
    } catch {
      return testUrl.includes(p);
    }
  });

  const handleCopy = () => {
    navigator.clipboard.writeText(robotsTxtContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    showToast('Copied!', 'Copied robots.txt to clipboard.', 'success');
  };

  const handleDownload = () => {
    const check = canUseTool(tool);
    if (!check.allowed) {
      showToast('Notice', check.reason || 'Upgrade required.', 'error');
      return;
    }

    const blob = new Blob([robotsTxtContent], { type: 'text/plain;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'robots.txt';
    link.click();

    recordConversion(tool, 'robots.txt');
    showToast('Downloaded!', 'Saved robots.txt to downloads.', 'success');
  };

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div className="space-y-1.5">
          <label className="text-xs font-semibold uppercase text-slate-500">Sitemap XML URL</label>
          <input
            type="url"
            value={sitemapUrl}
            onChange={(e) => setSitemapUrl(e.target.value)}
            className="w-full px-4 py-2.5 rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-sm outline-none"
          />
        </div>

        <div className="flex items-center gap-3 pt-6">
          <input
            type="checkbox"
            id="allowAll"
            checked={allowAll}
            onChange={(e) => setAllowAll(e.target.checked)}
            className="w-4 h-4 accent-indigo-600 rounded"
          />
          <label htmlFor="allowAll" className="text-sm font-medium text-slate-700 dark:text-slate-300">
            Allow all standard web crawlers by default
          </label>
        </div>
      </div>

      {/* Disallowed paths builder */}
      <div className="space-y-2">
        <label className="text-xs font-semibold uppercase text-slate-500">
          Disallow Crawler Paths
        </label>
        <div className="flex gap-2">
          <input
            type="text"
            value={newPath}
            onChange={(e) => setNewPath(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && addDisallow()}
            placeholder="/private-path"
            className="flex-1 px-4 py-2 rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-sm font-mono outline-none"
          />
          <button
            onClick={addDisallow}
            className="px-4 py-2 rounded-xl text-xs font-semibold text-white bg-indigo-600 hover:bg-indigo-500 flex items-center gap-1"
          >
            <Plus className="w-3.5 h-3.5" />
            <span>Add Path</span>
          </button>
        </div>

        <div className="flex flex-wrap gap-2 pt-2">
          {disallowPaths.map((p) => (
            <span
              key={p}
              className="inline-flex items-center gap-1.5 px-3 py-1 rounded-lg text-xs font-mono bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300"
            >
              <span>{p}</span>
              <button onClick={() => removeDisallow(p)} className="text-slate-400 hover:text-rose-500">
                ×
              </button>
            </span>
          ))}
        </div>
      </div>

      {/* Syntax Tester */}
      <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-850 border border-slate-200 dark:border-slate-700 space-y-2">
        <span className="text-xs font-bold uppercase text-slate-500">Live URL Directive Tester</span>
        <div className="flex flex-col sm:flex-row gap-2">
          <input
            type="text"
            value={testUrl}
            onChange={(e) => setTestUrl(e.target.value)}
            placeholder="Test URL (e.g. https://example.com/admin)"
            className="flex-1 px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-xs font-mono outline-none"
          />
          <div
            className={`px-3 py-1.5 rounded-lg text-xs font-bold flex items-center gap-1.5 shrink-0 ${
              isTestUrlBlocked
                ? 'bg-rose-500/10 text-rose-600 dark:text-rose-400 border border-rose-500/20'
                : 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20'
            }`}
          >
            <Shield className="w-3.5 h-3.5" />
            <span>{isTestUrlBlocked ? 'BLOCKED by robots.txt' : 'ALLOWED to crawl'}</span>
          </div>
        </div>
      </div>

      {/* Code preview & Action */}
      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <span className="text-xs font-semibold uppercase text-slate-500">
            Generated robots.txt Preview
          </span>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-600 text-xs font-medium text-slate-700 dark:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-700 flex items-center gap-1.5"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy'}</span>
            </button>
            <button
              onClick={handleDownload}
              className="px-4 py-1.5 rounded-lg font-semibold text-xs text-white bg-indigo-600 hover:bg-indigo-500 flex items-center gap-1.5 shadow-md"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download robots.txt</span>
            </button>
          </div>
        </div>

        <pre className="p-4 rounded-2xl bg-slate-950 text-cyan-300 font-mono text-xs overflow-x-auto border border-slate-800">
          {robotsTxtContent}
        </pre>
      </div>
    </div>
  );
}
